# version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: visualli-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: ./backend
    container_name: visualli-api
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/visualli
      PORT: 4000
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mongo-data: